# .github/workflows/deploy.yml

name: Deploy OpenLetter to AWS

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # Ativa o modo de depuração para vermos cada comando
            set -x

            # Passo 1: Atualiza o repositório
            echo "--- Atualizando o repositório ---"
            if [ -d "/home/ubuntu/OpenLetter" ] ; then
              cd /home/ubuntu/OpenLetter
              git pull origin main
            else
              git clone https://github.com/AndreyCortez/OpenLetter.git /home/ubuntu/OpenLetter
            fi

            # Passo 2: Cria os arquivos .env no local correto usando 'echo'
            echo "--- Criando arquivos de configuração ---"
            cd /home/ubuntu/OpenLetter/OpenLetterBackend
            pwd

            # Cria o arquivo .env.production para o backend
            echo "GO_ENV=production" > ./.env.production
            echo "DATABASE_URL=${{ secrets.PROD_DATABASE_URL }}" >> ./.env.production
            echo "JWT_SECRET=${{ secrets.PROD_JWT_SECRET }}" >> ./.env.production
            echo "API_PORT=8080" >> ./.env.production

            # Cria o arquivo db.env para o banco de dados
            echo "POSTGRES_USER=${{ secrets.PROD_POSTGRES_USER }}" > ./db.env
            echo "POSTGRES_PASSWORD=${{ secrets.PROD_POSTGRES_PASSWORD }}" >> ./db.env
            echo "POSTGRES_DB=openletters" >> ./db.env

            # Lista os arquivos para confirmar que foram criados
            echo "--- Verificando arquivos criados ---"
            ls -la

            # Passo 3: Executa o Docker Compose
            echo "--- Iniciando o deploy com Docker Compose ---"
            cd /home/ubuntu/AwsDeployAndreyCortez
            docker compose up -d --build --force-recreate --no-deps openletter-db openletter-backend openletter-frontend